<ul class="<?= $this->navigation()->menu()->getUlClass() ?>">       
    <?php foreach ($this->container as $page): ?>
        <?php if (!$page->isVisible() || !$this->navigation()->accept($page)) continue; ?>
        <?php $hasChildren = $page->hasPages() ?>
        <?php if (!$hasChildren or $page->getId() == 'orfan'): ?>
            <li<?php if ($page->isActive()) echo ' class="active"'; ?>>
                <a href="<?php echo $page->getHref() ?>">
                <?php if (null !== $page->get("icon")): ?>
                    <i class="<?php echo $page->get("icon"); ?>"></i>
                <?php endif; ?>                    
                    <?= $this->translate($page->getLabel()) ?>
                </a>
            </li>
        <?php else: ?>
            <li class="dropdown<?php if ($page->isActive(true)) echo ' active'; ?>">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <?php if (null !== $page->get("icon")): ?>
                    <i class="<?php echo $page->get("icon"); ?>"></i>
                <?php endif; ?>                     
                    <?= $this->translate($page->getLabel()) ?> <b class="caret"></b>
                </a>    
                <ul class="dropdown-menu">
                    <?php foreach ($page->getPages() as $child): ?>
                        <?php if (!$child->isVisible() || !$this->navigation()->accept($child)) continue; ?>
                        <li<?php if ($child->isActive()) echo ' class="active"'; ?>>
                            <a href="<?php echo $child->getHref() ?>">
                            <?php if (null !== $child->get("icon")): ?>
                                <i class="<?php echo $child->get("icon"); ?>"></i>
                            <?php endif; ?>                                 
                                <?= $this->translate($child->getLabel()) ?>
                            </a>
                        </li>
                    <?php endforeach ?>
                </ul>
            </li>
        <?php endif ?>
    <?php endforeach ?>
</ul>
